name: Deploy HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    run-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Show all files
      run: ls -al
    
